# Generated by Django 5.1.6 on 2026-08-15 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_article_body_source_article_legacy_id_and_more'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Primary key of the monolith NewsletterSubscriber row.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal name for the issue — not the email subject line.', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('subject', models.CharField(help_text='The subject line recipients saw. Shown in the archive as the issue heading, because it is what the issue actually said it was.', max_length=200)),
                ('body_html', models.TextField(blank=True, help_text='The issue body, as HTML. Rendered through .hs-prose.')),
                ('body_source', models.TextField(blank=True, help_text='The monolith HTML exactly as exported, before the import rewrote links. Kept so the rewriting is auditable; never rendered.')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, help_text='When this went out. Empty means a draft — drafts are never shown in the public archive.', null=True)),
                ('send_count', models.PositiveIntegerField(default=0, help_text='How many subscribers this issue went to.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('legacy_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Primary key of the monolith Newsletter this came from.', null=True, unique=True)),
                ('legacy_path', models.CharField(blank=True, help_text='Where this lived on haresign.net. Used for the redirect map.', max_length=255)),
                ('articles', models.ManyToManyField(blank=True, help_text='Insights featured in this issue.', related_name='newsletter_issues', to='insights.article')),
            ],
            options={
                'verbose_name': 'Newsletter issue',
                'verbose_name_plural': 'Newsletter issues',
                'ordering': ['-sent_at', '-created_at'],
            },
        ),
    ]
