# Generated by Django 5.1.6 on 2026-08-14 23:48

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='Used in the URL: /insights/<slug>/. Keep it stable once published — changing it breaks existing links.', max_length=255, unique=True)),
                ('kicker', models.CharField(blank=True, help_text='Short line above the headline, e.g. "Workforce". Optional.', max_length=120)),
                ('summary', models.TextField(help_text='One or two sentences. Shown on the index, on cards, and used as the meta description when none is set.')),
                ('body', tinymce.models.HTMLField(help_text='The article. Authored in TinyMCE and stored as HTML.')),
                ('author_name', models.CharField(default='Haresign', max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When this goes live. A future date schedules it: the article stays invisible until then, even when status is Published.', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Leads the Insights index and the homepage. The most recent featured article wins if several are ticked.')),
                ('featured_image', models.ImageField(blank=True, upload_to='insights/%Y/%m/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Describes the image for screen readers. Leave empty only if the image is purely decorative.', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='Falls back to the title.', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Falls back to the summary.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='articles', to='insights.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='insights.tag')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='insights_ar_status_8e8ebb_idx')],
            },
        ),
    ]
