# Generated by Django 5.1.6 on 2026-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_source',
            field=models.TextField(blank=True, help_text='The monolith HTML exactly as exported, before the import rewrote links and removed dead controls. Kept so the rewriting is auditable and re-runnable; never rendered.'),
        ),
        migrations.AddField(
            model_name='article',
            name='legacy_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Primary key of the monolith BlogPost this came from. The import matches on this before falling back to slug, so a slug corrected on either side cannot create a second copy.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='legacy_path',
            field=models.CharField(blank=True, help_text='Where this lived on haresign.net, e.g. /blog/<slug>/. Used to build the cutover redirect map.', max_length=255),
        ),
    ]
